name: example
description: example

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
environment:
  sdk: ">=3.1.0-94.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  test: ^1.24.3
  cupertino_icons: ^1.0.5
  cupertino_menu:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
